-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account
(

    CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY (id),
    CONSTRAINT "UQ_77bf26eef8865441fb9bd53a364" UNIQUE ("roleId"),
    CONSTRAINT "UQ_f3b3cc282091806bc6775a83411" UNIQUE ("userIdId")
);

CREATE TABLE IF NOT EXISTS public."chat-box"
(

    CONSTRAINT "PK_625ae4965064753d5db598ffe6c" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."chat-group"
(

    CONSTRAINT "PK_453cf4cdd708a84f82a40fc7827" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."chat-group_user_id_user_base"
(

    CONSTRAINT "PK_694cc8050640f9b9617ec923b02" PRIMARY KEY ("chatGroupId", "userBaseId")
);

CREATE TABLE IF NOT EXISTS public."group-leader-permission"
(

    CONSTRAINT "PK_f92ab6d533704483f0682dbae8d" PRIMARY KEY (id),
    CONSTRAINT "UQ_2dae2c53999616ea9f47ad24ba5" UNIQUE ("permissionIdId")
);

CREATE TABLE IF NOT EXISTS public.message
(

    CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permission
(

    CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY (id),
    CONSTRAINT "UQ_c7058daaafc4209c1d3d10ea48c" UNIQUE ("groupLeaderPermissionIdId")
);

CREATE TABLE IF NOT EXISTS public.role
(

    CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY (id),
    CONSTRAINT "UQ_09638bc4a92d385893789996a0c" UNIQUE ("accountIdId")
);

CREATE TABLE IF NOT EXISTS public.user_base
(

    CONSTRAINT "PK_abddcf5bb4dde7a5fe7b85b716c" PRIMARY KEY (id),
    CONSTRAINT "UQ_3bb7ed4ea11075fecfa7c047e13" UNIQUE ("accountIdId")
);

CREATE TABLE IF NOT EXISTS public."user_base_chat_group_id_chat-group"
(

    CONSTRAINT "PK_759b634ffa5cd14f9a21fd985db" PRIMARY KEY ("userBaseId", "chatGroupId")
);

ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT "FK_77bf26eef8865441fb9bd53a364" FOREIGN KEY ("roleId")
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "UQ_77bf26eef8865441fb9bd53a364"
    ON public.account("roleId");


ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT "FK_f3b3cc282091806bc6775a83411" FOREIGN KEY ("userIdId")
    REFERENCES public.user_base (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "UQ_f3b3cc282091806bc6775a83411"
    ON public.account("userIdId");


ALTER TABLE IF EXISTS public."chat-box"
    ADD CONSTRAINT "FK_5c26ddd7a0e9be82f32bfbcd117" FOREIGN KEY ("messageIdId")
    REFERENCES public.message (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."chat-group"
    ADD CONSTRAINT "FK_5a474dde00b478b6552903380e1" FOREIGN KEY ("groupLeaderPermissionIdId")
    REFERENCES public."group-leader-permission" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."chat-group"
    ADD CONSTRAINT "FK_cac3572b3977663f0b97842a7ca" FOREIGN KEY ("messageIdId")
    REFERENCES public.message (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."chat-group_user_id_user_base"
    ADD CONSTRAINT "FK_762b0e017465e451efcf8ca931c" FOREIGN KEY ("userBaseId")
    REFERENCES public.user_base (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_762b0e017465e451efcf8ca931"
    ON public."chat-group_user_id_user_base"("userBaseId");


ALTER TABLE IF EXISTS public."chat-group_user_id_user_base"
    ADD CONSTRAINT "FK_b23134b38e764aa9bfc3ea69e46" FOREIGN KEY ("chatGroupId")
    REFERENCES public."chat-group" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_b23134b38e764aa9bfc3ea69e4"
    ON public."chat-group_user_id_user_base"("chatGroupId");


ALTER TABLE IF EXISTS public."group-leader-permission"
    ADD CONSTRAINT "FK_2dae2c53999616ea9f47ad24ba5" FOREIGN KEY ("permissionIdId")
    REFERENCES public.permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "UQ_2dae2c53999616ea9f47ad24ba5"
    ON public."group-leader-permission"("permissionIdId");


ALTER TABLE IF EXISTS public.permission
    ADD CONSTRAINT "FK_c7058daaafc4209c1d3d10ea48c" FOREIGN KEY ("groupLeaderPermissionIdId")
    REFERENCES public."group-leader-permission" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "UQ_c7058daaafc4209c1d3d10ea48c"
    ON public.permission("groupLeaderPermissionIdId");


ALTER TABLE IF EXISTS public.role
    ADD CONSTRAINT "FK_09638bc4a92d385893789996a0c" FOREIGN KEY ("accountIdId")
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "UQ_09638bc4a92d385893789996a0c"
    ON public.role("accountIdId");


ALTER TABLE IF EXISTS public.user_base
    ADD CONSTRAINT "FK_3bb7ed4ea11075fecfa7c047e13" FOREIGN KEY ("accountIdId")
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "UQ_3bb7ed4ea11075fecfa7c047e13"
    ON public.user_base("accountIdId");


ALTER TABLE IF EXISTS public.user_base
    ADD CONSTRAINT "FK_58bdd5d98874bfb414d9d5756c9" FOREIGN KEY ("groupLeaderPermissionIdId")
    REFERENCES public."group-leader-permission" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_base
    ADD CONSTRAINT "FK_de0e8e4934f20fa11f0cfebf745" FOREIGN KEY ("chatBoxIdId")
    REFERENCES public."chat-box" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."user_base_chat_group_id_chat-group"
    ADD CONSTRAINT "FK_4e26fe0d284825e1bf2f2a3fbba" FOREIGN KEY ("chatGroupId")
    REFERENCES public."chat-group" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_4e26fe0d284825e1bf2f2a3fbb"
    ON public."user_base_chat_group_id_chat-group"("chatGroupId");


ALTER TABLE IF EXISTS public."user_base_chat_group_id_chat-group"
    ADD CONSTRAINT "FK_6adc890ca2b71858c377a40efaa" FOREIGN KEY ("userBaseId")
    REFERENCES public.user_base (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_6adc890ca2b71858c377a40efa"
    ON public."user_base_chat_group_id_chat-group"("userBaseId");

END;