-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account
(

    CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY (id),
    CONSTRAINT "REL_3e6997fa71268151173f4c5670" UNIQUE ("roleId", "roleRoleId"),
    CONSTRAINT "REL_60328bf27019ff5498c4b97742" UNIQUE ("userId")
);

CREATE TABLE IF NOT EXISTS public."chat-box"
(

    CONSTRAINT "PK_131bb3d22b0aec43cabc03bb625" PRIMARY KEY (id, "chatBoxId")
);

CREATE TABLE IF NOT EXISTS public."chat-group"
(

    CONSTRAINT "PK_43ab706c9ff4061a1c337d10af0" PRIMARY KEY (id, "groupId")
);

CREATE TABLE IF NOT EXISTS public."chat-group_user_user_base"
(

    CONSTRAINT "PK_3cbb5084dee43bc21d5dfae57a4" PRIMARY KEY ("chatGroupId", "chatGroupGroupId", "userBaseId")
);

CREATE TABLE IF NOT EXISTS public."group-leader-permission"
(

    CONSTRAINT "PK_0ce004be81ab7871075fba3788f" PRIMARY KEY (id, "group_leader_permissionId"),
    CONSTRAINT "REL_e2d36e9c70602d556b0669f92a" UNIQUE ("permissionId")
);

CREATE TABLE IF NOT EXISTS public.message
(

    CONSTRAINT "PK_ddee9a39574a40151edb4edc87a" PRIMARY KEY (id, "messageId")
);

CREATE TABLE IF NOT EXISTS public.permission
(

    CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY (id),
    CONSTRAINT "REL_73e017f2235f89e88b7edb0079" UNIQUE ("groupLeaderPermissionId", "groupLeaderPermissionGroupLeaderPermissionId")
);

CREATE TABLE IF NOT EXISTS public.role
(

    CONSTRAINT "PK_54b53941aa6e0cc294eb17f972c" PRIMARY KEY (id, "roleId"),
    CONSTRAINT "REL_0a76bde8a84a06826b65bcaaf3" UNIQUE ("accountId")
);

CREATE TABLE IF NOT EXISTS public.user_base
(

    CONSTRAINT "PK_abddcf5bb4dde7a5fe7b85b716c" PRIMARY KEY (id),
    CONSTRAINT "REL_4b44fa1b51b36a749508884fd1" UNIQUE ("accountId")
);

CREATE TABLE IF NOT EXISTS public."user_base_chat_group_chat-group"
(

    CONSTRAINT "PK_35d4211e5fa19ed86d5ab78e707" PRIMARY KEY ("userBaseId", "chatGroupId", "chatGroupGroupId")
);

ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT "FK_3e6997fa71268151173f4c56701" FOREIGN KEY ("roleId", "roleRoleId")
    REFERENCES public.role (id, "roleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "REL_3e6997fa71268151173f4c5670"
    ON public.account("roleId", "roleRoleId");


ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT "FK_60328bf27019ff5498c4b977421" FOREIGN KEY ("userId")
    REFERENCES public.user_base (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "REL_60328bf27019ff5498c4b97742"
    ON public.account("userId");


ALTER TABLE IF EXISTS public."chat-box"
    ADD CONSTRAINT "FK_b3da190dfcfe9f417d396e82620" FOREIGN KEY ("messageId", "messageMessageId")
    REFERENCES public.message (id, "messageId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."chat-group"
    ADD CONSTRAINT "FK_20889cba4bba482c4f924515572" FOREIGN KEY ("groupLeaderPermissionId", "groupLeaderPermissionGroupLeaderPermissionId")
    REFERENCES public."group-leader-permission" (id, "group_leader_permissionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."chat-group"
    ADD CONSTRAINT "FK_d51b9793e2711490d64a95aecbe" FOREIGN KEY ("messageId", "messageMessageId")
    REFERENCES public.message (id, "messageId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."chat-group_user_user_base"
    ADD CONSTRAINT "FK_57298e245506755519ef909543b" FOREIGN KEY ("userBaseId")
    REFERENCES public.user_base (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IDX_57298e245506755519ef909543"
    ON public."chat-group_user_user_base"("userBaseId");


ALTER TABLE IF EXISTS public."chat-group_user_user_base"
    ADD CONSTRAINT "FK_b609d5163910994f9ebdbc15851" FOREIGN KEY ("chatGroupId", "chatGroupGroupId")
    REFERENCES public."chat-group" (id, "groupId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_b609d5163910994f9ebdbc1585"
    ON public."chat-group_user_user_base"("chatGroupId", "chatGroupGroupId");


ALTER TABLE IF EXISTS public."group-leader-permission"
    ADD CONSTRAINT "FK_e2d36e9c70602d556b0669f92a1" FOREIGN KEY ("permissionId")
    REFERENCES public.permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "REL_e2d36e9c70602d556b0669f92a"
    ON public."group-leader-permission"("permissionId");


ALTER TABLE IF EXISTS public.permission
    ADD CONSTRAINT "FK_73e017f2235f89e88b7edb00797" FOREIGN KEY ("groupLeaderPermissionId", "groupLeaderPermissionGroupLeaderPermissionId")
    REFERENCES public."group-leader-permission" (id, "group_leader_permissionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "REL_73e017f2235f89e88b7edb0079"
    ON public.permission("groupLeaderPermissionId", "groupLeaderPermissionGroupLeaderPermissionId");


ALTER TABLE IF EXISTS public.role
    ADD CONSTRAINT "FK_0a76bde8a84a06826b65bcaaf3c" FOREIGN KEY ("accountId")
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "REL_0a76bde8a84a06826b65bcaaf3"
    ON public.role("accountId");


ALTER TABLE IF EXISTS public.user_base
    ADD CONSTRAINT "FK_23f93f8e4c05a1ec306445c2611" FOREIGN KEY ("chatBoxId", "chatBoxChatBoxId")
    REFERENCES public."chat-box" (id, "chatBoxId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_base
    ADD CONSTRAINT "FK_4b44fa1b51b36a749508884fd1c" FOREIGN KEY ("accountId")
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "REL_4b44fa1b51b36a749508884fd1"
    ON public.user_base("accountId");


ALTER TABLE IF EXISTS public.user_base
    ADD CONSTRAINT "FK_99044aaf688be1f4795039f52d0" FOREIGN KEY ("groupLeaderPermissionId", "groupLeaderPermissionGroupLeaderPermissionId")
    REFERENCES public."group-leader-permission" (id, "group_leader_permissionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."user_base_chat_group_chat-group"
    ADD CONSTRAINT "FK_18c7b291a7f4a544e754005e3c1" FOREIGN KEY ("userBaseId")
    REFERENCES public.user_base (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_18c7b291a7f4a544e754005e3c"
    ON public."user_base_chat_group_chat-group"("userBaseId");


ALTER TABLE IF EXISTS public."user_base_chat_group_chat-group"
    ADD CONSTRAINT "FK_edeb8cebfd37710abd5ebf522f9" FOREIGN KEY ("chatGroupId", "chatGroupGroupId")
    REFERENCES public."chat-group" (id, "groupId") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_edeb8cebfd37710abd5ebf522f"
    ON public."user_base_chat_group_chat-group"("chatGroupId", "chatGroupGroupId");

END;